name: Windows-RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
    - name: Download and Install ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
        Copy-Item ngrok\ngrok.exe C:\Windows\System32
      
    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.RDP_PASSWORD }}" -Force)
      
    - name: Create ngrok Tunnel
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok tcp 3389 --log=stdout > ngrok.log &
        Start-Sleep -Seconds 10
        Get-Content ngrok.log
      
    - name: Connect to RDP (Keep Alive)
      run: |
        ping -n 360 127.0.0.1 > nul
