name: Windows-RDP-Fixed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
    - name: Download and Install Latest ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -Force
        .\ngrok\ngrok.exe --version
      
    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.RDP_PASSWORD }}" -Force)
      
    - name: Check for existing ngrok sessions
      run: |
        Write-Host "⚠️ IMPORTANT: Please check https://dashboard.ngrok.com/tunnels/agents"
        Write-Host "⚠️ If there are any existing sessions, terminate them before proceeding"
        Write-Host "⚠️ Then manually restart this workflow"
        Start-Sleep -Seconds 10
      
    - name: Create ngrok Tunnel
      run: |
        .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
        Start-Sleep -Seconds 5
      
    - name: Get Tunnel Info
      run: |
        try {
          $tunnelInfo = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels -ErrorAction Stop
          $tunnelUrl = $tunnelInfo.tunnels[0].public_url
          Write-Host "==============================================="
          Write-Host "✅ NGROK TUNNEL CREATED SUCCESSFULLY: $tunnelUrl"
          Write-Host "✅ CONNECT USING REMOTE DESKTOP WITH:"
          Write-Host "   Computer: $($tunnelUrl.Replace('tcp://', ''))"
          Write-Host "   Username: runneradmin"
          Write-Host "   Password: (Your RDP_PASSWORD secret)"
          Write-Host "==============================================="
        } catch {
          Write-Host "❌ Failed to get tunnel info: $_"
          Write-Host "❌ Please check ngrok dashboard at https://dashboard.ngrok.com/"
        }
      
    - name: Keep Alive
      run: |
        Write-Host "Keeping session alive for 6 hours..."
        $duration = 6 * 60 * 60
        $startTime = Get-Date
        while ((Get-Date) -lt $startTime.AddSeconds($duration)) {
          $elapsedTime = ((Get-Date) - $startTime).TotalMinutes
          $remainingTime = [Math]::Max(0, $duration/60 - $elapsedTime)
          Write-Host "Session active. Remaining time: $([Math]::Round($remainingTime, 2)) minutes"
          Start-Sleep -Seconds 300
        }
